### ISSUE TITLE
On Ubuntu/Xubuntu the software will not launch

### ISSUE THREAD

**Issue by investor472** [girino/grpcticketstatus#1]
pip and the three other dependencies were installed.  The result is below.  I understand the main page says it is not functional.  If I am barking up the wrong tree please let me know.  TIA
```
user-name@xubuntu:~/Downloads$ sudo ./ticketstatus-tk-linux_amd64-0_1_1
[sudo] password for user-name: 
Traceback (most recent call last):
  File "ticketstatus-tk.py", line 5, in <module>
  File "/tmp/pip-install-4EZCNE/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "tkinter/__init__.py", line 5, in <module>
  File "/tmp/pip-install-4EZCNE/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib-tk/Tkinter.py", line 42, in <module>
ImportError: No module named _tkinter, please install the python-tk package
[4148] Failed to execute script ticketstatus-tk

user-name@xubuntu:~/Downloads$ sudo apt-get install python-tk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  blt libtcl8.6 libtk8.6 tk8.6-blt2.5
Suggested packages:
  blt-demo tcl8.6 tk8.6 tix python-tk-dbg
The following NEW packages will be installed:
  blt libtcl8.6 libtk8.6 python-tk tk8.6-blt2.5
0 upgraded, 5 newly installed, 0 to remove and 53 not upgraded.
Need to get 2,178 kB of archives.
After this operation, 8,438 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 libtcl8.6 amd64 8.6.8+dfsg-3 [881 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 libtk8.6 amd64 8.6.8-4 [693 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 tk8.6-blt2.5 amd64 2.5.3+dfsg-4 [572 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 blt amd64 2.5.3+dfsg-4 [4,944 B]
Get:5 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 python-tk amd64 2.7.15~rc1-1 [25.9 kB]
Fetched 2,178 kB in 3s (678 kB/s)    
Selecting previously unselected package libtcl8.6:amd64.
(Reading database ... 184418 files and directories currently installed.)
Preparing to unpack .../libtcl8.6_8.6.8+dfsg-3_amd64.deb ...
Unpacking libtcl8.6:amd64 (8.6.8+dfsg-3) ...
Selecting previously unselected package libtk8.6:amd64.
Preparing to unpack .../libtk8.6_8.6.8-4_amd64.deb ...
Unpacking libtk8.6:amd64 (8.6.8-4) ...
Selecting previously unselected package tk8.6-blt2.5.
Preparing to unpack .../tk8.6-blt2.5_2.5.3+dfsg-4_amd64.deb ...
Unpacking tk8.6-blt2.5 (2.5.3+dfsg-4) ...
Selecting previously unselected package blt.
Preparing to unpack .../blt_2.5.3+dfsg-4_amd64.deb ...
Unpacking blt (2.5.3+dfsg-4) ...
Selecting previously unselected package python-tk.
Preparing to unpack .../python-tk_2.7.15~rc1-1_amd64.deb ...
Unpacking python-tk (2.7.15~rc1-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up libtcl8.6:amd64 (8.6.8+dfsg-3) ...
Setting up libtk8.6:amd64 (8.6.8-4) ...
Setting up tk8.6-blt2.5 (2.5.3+dfsg-4) ...
Setting up blt (2.5.3+dfsg-4) ...
Setting up python-tk (2.7.15~rc1-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

user-name@xubuntu:~/Downloads$ sudo ./ticketstatus-tk-linux_amd64-0_1_1
Traceback (most recent call last):
  File "ticketstatus-tk.py", line 5, in <module>
  File "/tmp/pip-install-4EZCNE/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "tkinter/__init__.py", line 5, in <module>
  File "/tmp/pip-install-4EZCNE/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib-tk/Tkinter.py", line 42, in <module>
ImportError: No module named _tkinter, please install the python-tk package
[4264] Failed to execute script ticketstatus-tk
```

**Comment by girino** [comment]
I think this might have to do with python version. Can you try the following command?

`apt-get install python3-tk`

and try again?
Thanks.

**Comment by investor472** [comment]
sudo apt-get install python3-tk
[sudo] password for user-name: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  tix python3-tk-dbg
The following NEW packages will be installed:
  python3-tk
0 upgraded, 1 newly installed, 0 to remove and 44 not upgraded.
Need to get 100 kB of archives.
After this operation, 889 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 python3-tk amd64 3.6.5-3 [100 kB]
Fetched 100 kB in 1s (194 kB/s)      
Selecting previously unselected package python3-tk:amd64.
(Reading database ... 186893 files and directories currently installed.)
Preparing to unpack .../python3-tk_3.6.5-3_amd64.deb ...
Unpacking python3-tk:amd64 (3.6.5-3) ...
Setting up python3-tk:amd64 (3.6.5-3) ...

user-name@xubuntu:~/Downloads$ sudo ./ticketstatus-tk-linux_amd64-0_1_1
Traceback (most recent call last):
  File "ticketstatus-tk.py", line 5, in <module>
  File "/tmp/pip-install-4EZCNE/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "tkinter/__init__.py", line 5, in <module>
  File "/tmp/pip-install-4EZCNE/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "lib-tk/Tkinter.py", line 42, in <module>
ImportError: No module named _tkinter, please install the python-tk package
[6308] Failed to execute script ticketstatus-tk

**Comment by girino** [comment]
can you please check wich version of python you are running with `python --version`?

**Comment by investor472** [comment]
Python 2.7.15rc1
I am on Slack, Telegram etc. if that is easier.

**Comment by girino** [comment]
I generated this new linux file (newer version of code) could you try it and see if it works?

http://girino.org/grpcticketstatus/ticketstatus-tk-linux_amd64-0_1_2

**Comment by investor472** [comment]
udo ./ticketstatus-tk-linux_amd64-0_1_2
[sudo] password for user-name: 
requesting blocks from 0 to 19999
requesting blocks from 20000 to 39999
requesting blocks from 40000 to 59999
requesting blocks from 60000 to 79999
requesting blocks from 80000 to 99999
requesting blocks from 100000 to 119999
requesting blocks from 120000 to 139999
requesting blocks from 140000 to 159999
requesting blocks from 160000 to 179999
requesting blocks from 180000 to 199999
requesting blocks from 200000 to 219999
requesting blocks from 220000 to 239999
requesting blocks from 240000 to 259999
requesting blocks from 260000 to 279999
Traceback (most recent call last):
  File "ticketstatus-tk.py", line 300, in <module>
  File "ticketstatus-tk.py", line 272, in __init__
  File "ticketstatus-tk.py", line 213, in __init__
  File "ticketstatus-tk.py", line 84, in __init__
  File "lib-tk/Tkinter.py", line 2031, in grid_configure
_tkinter.TclError: cannot use geometry manager grid inside .140191182278240 which already has slaves managed by pack
[7904] Failed to execute script ticketstatus-tk

**Comment by girino** [comment]
I tried to fix this new issue. tested on a docker instance. seems to be ok. please try it:

http://girino.org/grpcticketstatus/ticketstatus-tk-linux_amd64-0_1_2b

**Comment by investor472** [comment]
Success!  Thank you.
